---

- name: install Python 3 and numpy on Debian
  package: name={{ item }} state=present
  with_items:
    - ipython3
    - python3-numpy
  when: ansible_os_family == 'Debian'
  become: true


- name: install Python 3 and numpy on ALT Linux
  package: name={{ item }} state=present
  with_items:
    - python3
    - python3-module-numpy
  when: ansible_os_family == 'Altlinux'
  become: true

- name: install gcc version 10 on Debian
  package: name={{ item }} state=present
  with_items:
    - gcc-10
  when: ansible_os_family == 'Debian'
  become: true

- name: install gcc version 10 on ALT Linux
  package: name={{ item }} state=present
  with_items:
    - gcc10
    - glibc-devel-static
  when: ansible_os_family == 'Altlinux'
  become: true

- name: install perf on Ubuntu/Debian
  package: name=linux-tools-common state=present
  when: ansible_os_family == 'Debian'
  become: true

- name: figure out kernel flavour
  command: uname -r
  register: uname_r
  changed_when: False
  when: ansible_os_family == 'Debian'

- name: install perf for current kernel version
  package:
    name: "linux-tools-{{ uname_r.stdout_lines[0] }}"
    state: present
  when: ansible_os_family == 'Debian'
  become: true

- name: install perf on ALT Linux
  package: name=perf state=present
  when: ansible_os_family == 'Altlinux'
  become: true

- name: install ninja
  package: name=ninja-build state=present
  become: true

- name: install perl on ALT Linux
  package: name=perl-base state=present
  when: ansible_os_family == 'Altlinux'
  become: true
